name: API Tests Pipeline

on:
  workflow_dispatch:      # Bisa dijalankan manual
  pull_request:           # Jalan otomatis saat ada PR ke main
    branches: [ main ]
  push:                   # (Opsional) Jalan saat push ke main
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      # Menjalankan tes API. Pastikan task 'test' menjalankan runner API Anda.
      # Jika Anda menggunakan tag, perintahnya seperti di bawah:
      - name: Run API Tests
        run: ./gradlew clean test -Dcucumber.filter.tags="@api"
        env:
          APP_ID: ${{ secrets.APP_ID }}

      # Upload Report agar bisa didownload
      - name: Upload API Test Report
        if: always() # Report tetap di-upload meski tes gagal
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: build/reports/cucumber/
          retention-days: 7