name: Web UI Tests Pipeline

on:
  workflow_dispatch:
  pull_request:           # Jalan otomatis saat ada PR ke main
    branches: [ main ]
  push:                   # Jalan saat push ke main
    branches: [ main ]

jobs:
  web-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Install Chrome untuk Selenium
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      # Menjalankan tes Web.
      # Menggunakan tag @web untuk memfilter tes UI saja
      - name: Run Web Tests
        # Gunakan mode headless agar jalan di server Ubuntu (tanpa layar)
        run: ./gradlew clean test -Dcucumber.filter.tags="@web" -Dheadless=true
        env:
          BROWSER: chrome

      # Upload Report agar bisa didownload
      - name: Upload Web Test Report
        if: always() # Report tetap di-upload meski tes gagal
        uses: actions/upload-artifact@v4
        with:
          name: web-test-report
          path: build/reports/cucumber/ # Path output HTML report
          retention-days: 7